#  youtube-web - Youtube webapp for Ubuntu Touch
#  Copyright (C) 2021 A. Semphris <semphris@protonmail.com>
#                2021 Mateo Salta <mateo_salta@yahoo.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

name: Build
on: [workflow_dispatch]

jobs:
  ubuntu-touch:
    strategy:
      fail-fast: false
      matrix:
         build: [Release, Debug]
         arch: [armhf, arm64, amd64]
         version: ['refs/tags/5.2.1-ekshi']

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install clickable
        run: |
          # For whatever reason, I have to manually install runc before docker.io or containerd, else it fails because of broken dependency
          # Using apt-get because apt complains it shouldn't be used in scripts
          sudo apt-get update
          sudo apt-get install -y runc
          sudo apt-get install -y docker.io adb git python3 python3-pip
          pip3 install --user git+https://gitlab.com/clickable/clickable.git@debug
          # Clickable requires a reboot/logout. This is a sneaky way to bypass that :^)
          sudo systemctl unmask docker.service
          sudo systemctl start docker.service
      - name: Build
        env:
          BUILD_TYPE: ${{ (matrix.build == 'Debug') && '--debug' || '' }}
          ARCH: ${{ matrix.arch }}
        run: ~/.local/bin/clickable build --verbose ${BUILD_TYPE} --arch ${ARCH} --config clickable.json
      - uses: actions/upload-artifact@v2
        with:
          name: "ubports-${{ matrix.arch }}--click"
          path: "build/*/app/*.click"
          if-no-files-found: ignore
